### ISSUE TITLE
TypeError: this.timeout.unref is not a function

### ISSUE THREAD

**Issue by mrawji** [iccicci/rotating-file-stream#106]
Hello,

After the refactor from 22c30a4df656e7f5ae923d39dcc4d74a6b6291c1, it looking like the fix from 1eda87ab4dae5ff41896b67833c2df5e4b2e2791 was lost. The original issue was #46

Would it be possible to re-apply the patch?

I am working within obsidian.md, which is an Electron app and I am getting this error:

```
Uncaught (in promise) TypeError: this.timeout.unref is not a function
```

For testing purposes, used version 2.1.5 which has the `import { setTimeout } from "timers";` line and it don't get the error anymore.

Thanks!!
Marc

**Comment by iccicci** [comment]
😨 Hi @mrawji ,

Honestly I have no idea about the implications of the change you are requesting, anyway if you know it may help under given circumstances... applied in `v3.2.4`.

Please feel free to close the issue if this solves your problem or please give me some more context in order to try to investigate.

Thank you

**Comment by mrawji** [comment]
Sweet! Thank you! I'll do some more testing, but 99% sure that fixes it.

Adding some extra data for posterity.

Electron issue: https://github.com/electron/electron/issues/21162
Node Timers: https://nodejs.org/api/timers.html
