### ISSUE TITLE
Rotate fails with applicatoin shutdown

### ISSUE THREAD

**Issue by tobilg** [iccicci/rotating-file-stream#14]
I see the following in my application's logs:

```javascript
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:193:12)
    at RotatingFileStream.Writable.write (_stream_writable.js:240:5)
    at Array.logRequest (/usr/local/dcos-universe-browser/node_modules/morgan/index.js:130:14)
    at listener (/usr/local/dcos-universe-browser/node_modules/on-finished/index.js:169:15)
    at onFinish (/usr/local/dcos-universe-browser/node_modules/on-finished/index.js:100:5)
    at callback (/usr/local/dcos-universe-browser/node_modules/ee-first/index.js:55:10)
    at ServerResponse.onevent (/usr/local/dcos-universe-browser/node_modules/ee-first/index.js:93:5)
    at emitNone (events.js:91:20)
    at ServerResponse.emit (events.js:185:7)
    at finish (_http_outgoing.js:596:10)
```

This occurs every night at 00:00 UTC. I use it like this:

```javascript
// Create a rotating write stream
var accessLogStream = rotatingFileStream(function(time, index) {
    if (!time) time = new Date();
    return 'access-' + time.toISOString().substr(0,10).split('-').join('') + '.log'
}, {
    interval: '1d',  // rotate daily
    path: logDirectory
});
```

Is there a hint where the problem can arise from? Thanks!

**Comment by iccicci** [comment]
Hi,

the first thing I see that could be cause of unexpected behaviour is:
```
if (!time) time = new Date();
```
in your _filename generator_.

This will cause your program to create the log file with a name which is function of the day when your program was launched.

I strongly suggest to change it in:
```
if (!time)
  return 'access.log';
```

Anyway I can't say if that is the root cause of the reported problem.

The error is clear: there is some _write_ attempt after a _close_ call.
**RotatingFileStream** will close by itself after an error... you can try to add an error event listener to check if that is the case:

```
accessLogStream.on('error', console.log.bind(console));
```

Please let me know about your progress with this issue.

Thank you,
iCC

**Comment by iccicci** [comment]
Hi man!

Any news about your issue?

**Comment by tobilg** [comment]
Hey @iccicci, thanks for your hints... I guess you're right regarding `time`. Works now.

**Comment by unliar** [comment]
```
let logStream = rfs((index) => {
  return `${moment().format('YYYYMMDD')}.log`
}, {
  interval: '1d',
  path: logDir
})
```
i meet the same error when i wana use the date to name my logs file.

**Comment by iccicci** [comment]
Your _filename generator_ function does not accept the _time_ parameter.
Change this and apply same change I already suggested...

**Comment by iccicci** [comment]
Hi @unliar ,

any news about your issue?

**Comment by unliar** [comment]
@iccicci   everything goes well.  many thanks for your help.
