### ISSUE TITLE
Cleanup and compress on application closing

### ISSUE THREAD

**Issue by jspaeth20** [iccicci/rotating-file-stream#39]
Is there a way to cleanup when the application is closing. I am currently calling the writable.end() method but that doesn't handle the compression of the current stream?

**Comment by iccicci** [comment]
Hi @jspaeth20 ,

that it is the right method to close the stream; probably its better to wait for the `close` event to be sure everything is done.
If you mean you expected an additional compression on stream close, this is not expected: rotations, and eventual compressions, happen only at time limit or size limit.

Hope this helps,
iCC

**Comment by puzsol** [comment]
I am having a similar issue, in that when the application shuts down (cancelled), the last file it was writing to is not recorded in the history file - which is a problem, because I am using the immutable flag with a filename based on date-time to the millisecond, so when it starts up, it generates a new file name and starts writing to it, when that file is rotated it is added to the history file, but it skips the one that was open when the application died - so it is never cleaned up.

Eg run 1:
FileA.log
FileB.log
FileC.log
were created but only FileA and FileB are recorded in the history file (as history is only appended to on stream close, not stream open)
run 2:
FileD.log is created
FileE.log is created, as we hit the limit, FileA is removed
FileF.log is created, FileB is removed
FileG.log is created, FileD is removed

Result is that FileC is never removed because it was never recorded in the history file.
Repeat this a few times and the log files start to pile up.

Is there some event I should be hooking into to ensure the last open log file is recorded before the application ends?

**Comment by iccicci** [comment]
Hi @puzsol ,

crystal clear! I'll check it soon.
