### ISSUE TITLE
Parameters of function as filename parameter are null/undefined

### ISSUE THREAD

**Issue by ppinel** [iccicci/rotating-file-stream#4]
Hello,

I am playing with this plugin but can't get the time parameter or index parameter.
time is `null` and index is `undefined`.
I am providing an interval and a path option.

Looking at the code: 
- Here the value of `this.generator` https://github.com/iccicci/rotating-file-stream/blob/master/index.js#L31
- It is used here https://github.com/iccicci/rotating-file-stream/blob/master/index.js#L130

I understand now why `time` is null and index is `undefined`. Is this normal?

**Comment by iccicci** [comment]
Hi, sorry for my late reply, I have been so busy on the past months.

Are you speaking about the first time your generator is called?
If your answer is yes, my answer is: yes, it is normal, the module calls your generator with _null_ parameters at beginning in order to know the _not rotated file name_ .

If your generator is always called with null parameters (first time and later ones), there is some problem.

If you are still interested, can you be more precise?
Thank you

**Comment by iccicci** [comment]
Closing due to lack of feedback

**Comment by ArtixZ** [comment]
@iccicci I'm having the same issue.
what does this mean:  

> "in order to know the not rotated file name ."

**Comment by iccicci** [comment]
Hi @ArtixZ,

can you please share the piece of code causing the issue?

Thank you,
iCC

**Comment by ArtixZ** [comment]
```javascript
function generator(time, idx) {
    return `cmnportal-${time.getFullYear()}-${time.getMonth()}_${time.getDate()}.log`
  }
const accessLogStream = rfs(generator, {
    interval: '1d', // rotate daily
    path: logDirectory
  })
```
I'm creating log with morgan. It will have the error when trying to run up the node server.

**Comment by iccicci** [comment]
Sure @ArtixZ !

Please take a look at this paragraph:
https://www.npmjs.com/package/rotating-file-stream#function-filenametime-index
Looking at your code I guess you probably could be interested to this other paragraph:
https://www.npmjs.com/package/rotating-file-stream#immutable

Please give me some feedback; closing the issue if those readings solve your problem is enough.

Thank you,
iCC

**Comment by iccicci** [comment]
Hi @ArtixZ ,

any news on this topic?

Thank you,
iCC

**Comment by ArtixZ** [comment]
Thanks for replying & sorry for responding late.
I've read these previously, but still wondering why the starting date is null. What if I want the the starting date when starting my server.

**Comment by iccicci** [comment]
Hi @ArtixZ ,

have you tried the _immutable_ option?

Please let me know,
iCC

**Comment by ArtixZ** [comment]
Yep. Immutable is working. 
Can you confirm if it works in this way without immutable:
`time` will be null, and I'm going to return a static file name. Once this rotation period is over, this static file will be renamed and a timestamp will be there in the name. Which means, the file will become a history.

**Comment by iccicci** [comment]
Hi @ArtixZ ,

I confirm, it works exactly as you described.

Thank you,
iCC
