### ISSUE TITLE
Error when logrotate and compressed a log file being tailed

### ISSUE THREAD

**Issue by FelixChow** [iccicci/rotating-file-stream#45]
Hi @iccicci ,

I have my stream config as follow:
`{
interval: '10s',
compress: (source, dest) => 'cat ${source} | gzip -c9 > ${dest}.gz',
maxFiles: 3
}`

I was monitoring the log file with tail -F,
when it comes to the rotation time,
it did not generate the .gz file and the writing stream was stopped

I have received the error message as follow:
`{ [Error: EPERM: operation not permitted, stat 'C:\git\***\log\access.log']
  errno: -4048,
  code: 'EPERM',
  syscall: 'stat',
  path: 'C:\\git\\***\\log\\access.log' }`

`Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed`
    `at doWrite (_stream_writable.js:411:19)`
    `at writeOrBuffer (_stream_writable.js:399:5)`
   ` at RotatingFileStream.Writable.write (_stream_writable.js:299:11)`

**Comment by iccicci** [comment]
Hi @FelixChow ,

first of all, which version of the package are you using?

From the error reported it's clear we are facing a permissions problem. Looking at the filename it seems to be the _not rotated filename_ while the reported problem is about rotation; this makes me think you have right privileges on that file. What I don't know is tail behavior under Windows. Could it be the root cause of the problem? Do you have the same experience without the tail command in execution?

As last (but this is not related with your problem), in your _compressor function_ you are adding `".gz"` at the destination file and you are using _history_ (`maxFiles: 3`); the package remembers the destination file it generates,  it can't know you are adding that extension; so _history_ won't work as expected.
If you want to add an extension to the filename it's better to use a _filename generator function_ doing that and keep untouched the destination file name in the _compressor function_.

Please let me know,
iCC

**Comment by FelixChow** [comment]
Hi @iccicci ,
I am using the latest v2.0.0
Actually the error was found on remote Linux machine first, and I reproduced it on local Windows.
My log file owner did not change during log rotation and the error only occurs when I am tailing the log files at the same time that the system is about to do log rotation.
I did not try the filename generator yet and I will update you ASAP.
Thank you so much!

**Comment by iccicci** [comment]
Hi @FelixChow ,

don't hurry, that's not related with the reported problem; it was just a side note.
While about the reported problem, I didn't understood if the problem occurs even if no tail is running; more than this, can you provide me the error you got under Linux?
As last, the errors you are speaking about, are just printed to the console or have you caught them through `"error"` and/or `"warning"` events?

Thank you,
iCC

**Comment by FelixChow** [comment]
Hi @iccicci ,
Thank you for your prompt response.
I can assure you there’s no problem if no tail is running.
I am currently not able to provide you the Linux log.
And the error is caught by the stream.on(error, console.log)

**Comment by iccicci** [comment]
Ok,

so the problem seems to be the presence of tail.
I'll work on it.

Thank you,
iCC

**Comment by iccicci** [comment]
Hi @FelixChow ,

I'm sorry but I was not able to reproduce the problem. I run this with tail -F on file.log but nothing than what I would have expected happened.

```javascript
const rfs = require(".");
const stream = rfs.createStream("file.log", {
  interval: "10s",
  compress: (source, dest) => `cat ${source} | gzip -c9 > ${dest}`,
  maxFiles: 3
});

const nothing = () => {
	stream.write("test\n");
	setTimeout(nothing, 1000);
};

stream.on("error", e => console.log("error", e));
stream.on("warning", e => console.log("warning", e));
nothing();
```

Are you able to provide me some more details or some relevant part of your code?

Thank you,
iCC

**Comment by FelixChow** [comment]
Hi @iccicci ,
More details like I was using pm2 cluster mode, I created multiple streams with rfs for both morgen and winston writestream. 
Currently I found that when running my project with pm2 cluster may lead to unlink error but not the stream was destroyed error.
Thank you so much.

**Comment by FelixChow** [comment]
Hi @iccicci ,

I use the filename generator you have mentioned earlier and combine with the process.env.pm_id to separate the log files for different thread somehow solved my problems.
Now I thought the problem should be caused by multiple thread but not your package.
Thank you so much for you help! I sincerely appreciate that. 

Felix

**Comment by iccicci** [comment]
Interesting!

I'll take care of this in next reviews of the package.
Thank you @FelixChow !
