### ISSUE TITLE
cannot find module "fs/promises" with nodejs 12.22.7

### ISSUE THREAD

**Issue by kapouer** [iccicci/rotating-file-stream#76]
and rfs 3.0.1

**Comment by kapouer** [comment]
See also the (somewhat hidden) "history" section of
https://nodejs.org/api/fs.html#promises-api
TL,DR: fs/promises not available in node 12, but was in 10 and is in 14.

**Comment by iccicci** [comment]
I'm so sorry @kapouer , the only solution I can provide you ATM is upgrading Node.js at least to v14.

It seems Node.js authors was a bit too much furious in changing the `fs/promises` interface.

I've asked on Stack Overflow too... if I can get an answer, I'll be pleased to solve this problem.
https://stackoverflow.com/questions/70041947/import-filehandle-across-node-js-versions

Sorry for the poor answer, but it is the maximum I was able to do.

**Comment by kapouer** [comment]
Well, likewise. I fell short of finding a workaround for that.
The only thing that needs to be fixed now is rotating-file-stream's package.json's engine field.

**Comment by iccicci** [comment]
v3.0.2 released

**Comment by mattberther** [comment]
According to https://stackoverflow.com/a/70042193, 

``` javascript 
const fileHandle = require("fs").promises;
```

works in Node versions v12, v14, and v16

**Comment by kapouer** [comment]
@mattberther the issue here is about es modules:
`import { FileHandle, mkdir, open, readFile, rename, stat, unlink, writeFile } from "fs/promises";`

**Comment by iccicci** [comment]
The problem is not only about the "fs/promises" import, @mattberther : many thing was changed in streams between Node.js v12 and v14.

Please check [tests result](https://app.travis-ci.com/github/iccicci/rotating-file-stream/jobs/553852167) in a branch where I solved the import problem: many other problems come out.

If you need to use **rotating-file-stream** on Node.js v12 (or lower), please use v2.1.6 which basically works exactly as v3 does.
