### ISSUE TITLE
Add total files limit option

### ISSUE THREAD

**Issue by dtryon** [iccicci/rotating-file-stream#8]
A nice option to add would be `totalFiles`.  This could limit the total number of files on disk at any moment.  This can be useful if disk is limited.

I think a good way to implement this would be to handle the 'rotated' event and keep a queue of filenames.  Then if the `totalFiles >= queue.length`, we could delete the oldest file.  Does this seem a reasonable way to implement?

Would the `firstOpen` be a good place to wire up the event handling?

**Comment by iccicci** [comment]
The complex part is :

> keep a queue of filenames

we have to take in account that the module should keep that queue even across multiple program shut down and restarts, so that queue should be kept at least in a separated file, but I strongly disapprove this solution.

On the other hands, due to the _generator_ function (which may generate so complex file names) is quite impossible to compute (at rotation time) how many files the module have already generated.

Once said that I think that this request couldn't be accomplished.

Anyway, using the standard **UNIX logrotate** behaviour, you can achieve your goal simply with the right configuration, otherwise you can easily make something (i.e. a crontab script) to remove files older than the threshold you need.

**Comment by dtryon** [comment]
Yes, I see how giving the flexibility of custom names for files is the problem here.  However, I don't think it is impossible.  The filename is generated before writes, so at the time it is materialized, it could be saved to another file that kept the queue.  This file could be nothing more than a serialized array of filenames.

I suppose there are a few corner cases like if the application crashed and the file that held the queue was slightly out of sync.

However, if you think this feature would be outside the scope of the project, I understand completely.

On my project, I was able to make it work with the 'rotated' event alone.  Just thought I could help contribute back if it was useful.  :)

**Comment by iccicci** [comment]
Yes, I agree everything you said, and I appreciated you made this request.

I just want to point, that I didn't said that it would be impossible (nor complicated) I just said I don't like the solution to have one more file to keep this information.

I'm fine you find to manage to solve your problem with the event handling.

I'll leave the issue open, so if it will find many other requestors, I'll do what you request (regardless what I like or not).

Thank you very much for your suggestion.

**Comment by iccicci** [comment]
Due to I hate having that terrible message (One open issue) on NPM page, requested feature was released with v1.2.0
